#!/bin/csh -f
if ($#argv == 0) then
   set n_line = `wc -l head3.lst`
   @ n_line = "$n_line[1]" - 1
   tail -"$n_line" head3.lst |cut -c7-20 > __junk.tmp
else
   egrep "$argv[1]" head3.lst |cut -c7-20 > __junk.tmp
endif

cut -c1-3  __junk.tmp > __junk1.tmp
cut -c6-14 __junk.tmp > __junk2.tmp
paste -d"." __junk1.tmp __junk2.tmp > __conf_list.tmp
set n_conf = `wc -l __conf_list.tmp`
@ n_conf = "$n_conf[1]"
echo $n_conf conformer files to make

if (! -d confs) mkdir confs
if (-f pymol_load.pml) then
   set stamp = `ls -l pymol_load.pml|cut -c35-99`
   mv pymol_load.pml pymol_load.pml."$stamp[1]"_"$stamp[2]"
endif

@ i_conf = 1
while($i_conf < $n_conf + 1)
   grep "`sed -n "$i_conf"p __conf_list.tmp`" step2_out.pdb > confs/"`sed -n "$i_conf"p __junk.tmp`".pdb
   echo load confs/"`sed -n "$i_conf"p __junk.tmp`".pdb >> pymol_load.pml
   @ i_conf = $i_conf + 1
end

rm -f __junk.tmp
rm -f __junk1.tmp
rm -f __junk2.tmp
rm -f __conf_list.tmp
